import type { TalentProfile } from "./types";

const talentAsset = (folder: string, file: string) => `case-site/cases/aigc-talent/${folder}/${file}`;

/**
 * 人才集市的初始数据。
 * 媒体文件先上传 OSS，再由这里写入稳定对象路径；应用启动时会把这份数据迁移到人才表。
 */
export const DEMO_TALENTS: TalentProfile[] = [
  {
    id: "ouyang",
    name: "欧阳",
    role: "AI视觉创作者 / AIGC内容运营",
    intro: "扎根消费品牌内容赛道，兼具内容审美与业务思维，持续把 AI 视觉与内容运营沉淀成可交付的商业作品。",
    bio: "擅长从选题策划、视觉生成到短视频产出与数据复盘，覆盖文旅宣传、产品广告和新媒体内容运营等方向。",
    avatarPath: talentAsset("avatars", "ouyang-v2.webp"),
    location: "深圳",
    skills: ["短视频剪辑", "影视海报", "AIGC插画", "数字人"],
    works: [
      {
        id: "ouyang-portfolio",
        slug: "site-k7m3x9p",
        title: "AI视觉创作者 / AIGC内容运营",
        type: "website",
        source: "static",
        summary: "个人案例网站，集中呈现视觉创作、商业短片和品牌内容运营作品。",
        coverPath: talentAsset("covers", "ouyang-portfolio.webp"),
        siteSlug: "site-k7m3x9p",
      },
    ],
  },
  {
    id: "lin-yifan",
    name: "林一凡",
    role: "AI视觉设计师 / 短视频创作者",
    intro: "主攻 AIGC 电商视觉设计，副线 AI 短视频内容运营，用视觉创意服务品牌表达和内容传播。",
    bio: "聚焦电商视觉、短视频内容和 AI 创意策划，形成从创意构思、视觉制作到内容交付的完整工作链路。",
    avatarPath: talentAsset("avatars", "lin-yifan.webp"),
    location: "深圳",
    skills: ["短视频剪辑", "影视海报", "AIGC插画"],
    works: [
      {
        id: "lin-qwenwork",
        slug: "lin-yifan-qwenwork",
        title: "AI视觉创作者 / 新媒体视觉设计 / AI创意策划",
        type: "website",
        source: "external",
        summary: "AIGC 内容运营、新媒体视觉设计与 AI 创意策划案例。",
        coverPath: talentAsset("covers", "lin-qwenwork.webp"),
        siteUrl: "https://wmy47gmh.qwenwork.host/",
      },
      {
        id: "lin-workbuddy",
        slug: "lin-yifan-workbuddy",
        title: "AI电商视觉设计师 / 短视频创作者",
        type: "website",
        source: "external",
        summary: "AI 电商视觉设计、短视频创作与品牌内容案例。",
        coverPath: talentAsset("covers", "lin-workbuddy.webp"),
        siteUrl: "https://f5389c591df64575ba7940b74b91b825.app.workbuddy.link/",
      },
    ],
  },
  {
    id: "li-na",
    name: "李娜",
    role: "AI短视频创作者 / AIGC内容剪辑",
    intro: "专注古装人物与生活化叙事，用 AI 把日常细节转化为有画面感的短视频。",
    bio: "擅长从人物动作、服饰质感和东方场景入手，完成 AI 短片的构思、生成与剪辑。",
    avatarPath: talentAsset("avatars", "li-na.webp"),
    location: "深圳",
    skills: ["AI影视分镜", "短视频剪辑", "数字人"],
    works: [
      {
        id: "li-na-video-01",
        slug: "li-na-video-01",
        title: "古装生活场景短片",
        type: "video",
        source: "uploaded",
        summary: "以古装人物整理衣物的生活化场景为切入点完成的 AI 剧情短片。",
        coverPath: talentAsset("covers", "cover-01-li-na.webp"),
        mediaPaths: [talentAsset("videos", "01-ancient-drama-washing.mp4")],
      },
    ],
  },
  {
    id: "wang-hao",
    name: "王浩然",
    role: "AI文旅影像创作者 / 视觉导演",
    intro: "关注传统建筑与地方人文，用 AI 影像记录有历史感的空间和旅行体验。",
    bio: "擅长提炼建筑轮廓、材质和光影关系，将传统文化场景转化为具有氛围感的文旅短片。",
    avatarPath: talentAsset("avatars", "wang-hao.webp"),
    location: "深圳",
    skills: ["AI影视分镜", "短视频剪辑", "AIGC插画"],
    works: [
      {
        id: "wang-hao-video-02",
        slug: "wang-hao-video-02",
        title: "传统建筑文旅影像",
        type: "video",
        source: "uploaded",
        summary: "以传统寺庙建筑为主体，呈现东方空间秩序与人文气息的 AI 文旅短片。",
        coverPath: talentAsset("covers", "cover-02-wang-hao.webp"),
        mediaPaths: [talentAsset("videos", "02-cultural-site.mp4")],
      },
    ],
  },
  {
    id: "zhang-min",
    name: "张敏",
    role: "AI文旅内容创作者 / 风光视觉设计师",
    intro: "擅长用山水镜头营造旅行情绪，为文旅内容寻找清晰、舒展的视觉表达。",
    bio: "从自然色彩、空间层次和镜头节奏出发，完成具有目的地识别度的 AI 风光影像。",
    avatarPath: talentAsset("avatars", "zhang-min.webp"),
    location: "深圳",
    skills: ["AI影视分镜", "短视频剪辑", "影视海报"],
    works: [
      {
        id: "zhang-min-video-03",
        slug: "zhang-min-video-03",
        title: "万绿湖山水宣传片",
        type: "video",
        source: "uploaded",
        summary: "围绕万绿湖碧水、群岛与晨雾景观制作的 AI 文旅宣传短片。",
        coverPath: talentAsset("covers", "cover-03-zhang-min.webp"),
        mediaPaths: [talentAsset("videos", "03-wanlv-lake.mp4")],
      },
    ],
  },
  {
    id: "liu-yang",
    name: "刘洋",
    role: "AI视觉设计师 / 文旅短视频创作者",
    intro: "喜欢从花田、乡野和季节变化中提取视觉灵感，探索轻盈自然的 AI 影像表达。",
    bio: "擅长以人物与环境的关系组织画面，让文旅短片同时具备风景展示和情绪感染力。",
    avatarPath: talentAsset("avatars", "liu-yang.webp"),
    location: "深圳",
    skills: ["短视频剪辑", "AIGC插画", "影视海报"],
    works: [
      {
        id: "liu-yang-video-04",
        slug: "liu-yang-video-04",
        title: "花田旅行短片",
        type: "video",
        source: "uploaded",
        summary: "以花田漫步为主题，营造轻松、明亮旅行氛围的 AI 视觉短片。",
        coverPath: talentAsset("covers", "cover-04-liu-yang.webp"),
        mediaPaths: [talentAsset("videos", "04-flower-field.mp4")],
      },
    ],
  },
  {
    id: "chen-jie",
    name: "陈杰",
    role: "AI短剧创作者 / 角色视觉设计师",
    intro: "专注古装人物和戏剧化镜头，用 AI 练习角色塑造与东方叙事的视觉节奏。",
    bio: "擅长从人物神态、服装细节和室内光影入手，制作具有故事开场感的 AI 角色短片。",
    avatarPath: talentAsset("avatars", "chen-jie.webp"),
    location: "深圳",
    skills: ["AI影视分镜", "短视频剪辑", "数字人"],
    works: [
      {
        id: "chen-jie-video-05",
        slug: "chen-jie-video-05",
        title: "古装人物剧情短片",
        type: "video",
        source: "uploaded",
        summary: "以宫廷人物近景和暖色室内光影为核心的 AI 古装剧情短片。",
        coverPath: talentAsset("covers", "cover-05-chen-jie.webp"),
        mediaPaths: [talentAsset("videos", "05-ancient-drama-palace.mp4")],
      },
    ],
  },
  {
    id: "yang-lei",
    name: "杨磊",
    role: "AI内容导演 / 三维短视频创作者",
    intro: "尝试用三维角色和轻喜剧设定讲述简单故事，让 AI 内容更有趣、更容易被记住。",
    bio: "擅长设计夸张但清晰的角色动作，结合东方幻想场景完成具有节奏感的趣味短视频。",
    avatarPath: talentAsset("avatars", "yang-lei.webp"),
    location: "深圳",
    skills: ["短视频剪辑", "数字人", "AIGC插画"],
    works: [
      {
        id: "yang-lei-video-06",
        slug: "yang-lei-video-06",
        title: "古风趣味剧情短片",
        type: "video",
        source: "uploaded",
        summary: "围绕古风角色与失灵折扇设定制作的轻松趣味 AI 三维短片。",
        coverPath: talentAsset("covers", "cover-06-yang-lei.webp"),
        mediaPaths: [talentAsset("videos", "06-ancient-drama-journey.mp4")],
      },
    ],
  },
  {
    id: "zhao-jing",
    name: "赵静怡",
    role: "AI商业视觉设计师 / 产品广告创作者",
    intro: "专注消费品视觉表达，用 AI 放大产品的色彩、质感和新鲜感。",
    bio: "擅长通过摄影式布光、微距细节和简洁构图，完成适合品牌传播的产品视觉内容。",
    avatarPath: talentAsset("avatars", "zhao-jing.webp"),
    location: "深圳",
    skills: ["影视海报", "短视频剪辑", "AIGC插画"],
    works: [
      {
        id: "zhao-jing-video-07",
        slug: "zhao-jing-video-07",
        title: "鲜橙产品广告",
        type: "video",
        source: "uploaded",
        summary: "用水珠、果肉和暖色光线突出鲜橙新鲜质感的 AI 产品广告短片。",
        coverPath: talentAsset("covers", "cover-07-zhao-jing.webp"),
        mediaPaths: [talentAsset("videos", "07-orange-ad.mp4")],
      },
    ],
  },
  {
    id: "huang-wei",
    name: "黄伟",
    role: "AI商业视觉创作者 / 品牌内容设计师",
    intro: "擅长把日用品放进具体生活场景，用 AI 做出柔和、有记忆点的品牌画面。",
    bio: "关注材质、色彩和生活方式氛围，能够从产品静物构图延展到完整的短视频广告表达。",
    avatarPath: talentAsset("avatars", "huang-wei.webp"),
    location: "深圳",
    skills: ["短视频剪辑", "影视海报", "数字人"],
    works: [
      {
        id: "huang-wei-video-08",
        slug: "huang-wei-video-08",
        title: "香氛洗护产品广告",
        type: "video",
        source: "uploaded",
        summary: "以粉色、洁白织物和花朵营造柔和香氛感的 AI 洗护产品广告。",
        coverPath: talentAsset("covers", "cover-08-huang-wei.webp"),
        mediaPaths: [talentAsset("videos", "08-laundry-ad.mp4")],
      },
    ],
  },
  {
    id: "wu-ting",
    name: "吴婷婷",
    role: "AI商业视觉设计师 / 生活方式内容创作者",
    intro: "关注精致生活方式与产品细节，探索 AI 在质感广告和社交内容中的应用。",
    bio: "擅长以夜景、材质反光和人物佩戴场景表现产品气质，完成高级感明确的商业短片。",
    avatarPath: talentAsset("avatars", "wu-ting.webp"),
    location: "深圳",
    skills: ["影视海报", "短视频剪辑", "AIGC插画"],
    works: [
      {
        id: "wu-ting-video-09",
        slug: "wu-ting-video-09",
        title: "腕表生活方式广告",
        type: "video",
        source: "uploaded",
        summary: "以玫瑰金腕表、城市夜景和佩戴细节营造精致氛围的 AI 广告短片。",
        coverPath: talentAsset("covers", "cover-09-wu-ting.webp"),
        mediaPaths: [talentAsset("videos", "09-watch-ad.mp4")],
      },
    ],
  },
  {
    id: "zhou-peng",
    name: "周鹏飞",
    role: "AI运动影像创作者 / 短视频导演",
    intro: "喜欢用第一视角和运动镜头制造现场感，让 AI 影像更有速度和参与感。",
    bio: "擅长把运动路线、光线变化和镜头运动结合起来，制作有冲击力的骑行与户外短片。",
    avatarPath: talentAsset("avatars", "zhou-peng.webp"),
    location: "深圳",
    skills: ["短视频剪辑", "AI影视分镜", "数字人"],
    works: [
      {
        id: "zhou-peng-video-10",
        slug: "zhou-peng-video-10",
        title: "骑行运动视觉短片",
        type: "video",
        source: "uploaded",
        summary: "用骑行第一视角呈现山路速度、光影和沉浸感的 AI 运动短片。",
        coverPath: talentAsset("covers", "cover-10-zhou-peng.webp"),
        mediaPaths: [talentAsset("videos", "10-bike-ad.mp4")],
      },
    ],
  },
];

export function getDemoTalent(talentId: string) {
  return DEMO_TALENTS.find((talent) => talent.id === talentId) ?? null;
}

export function getDemoWork(talentId: string, workSlug: string) {
  const talent = getDemoTalent(talentId);
  if (!talent) return null;
  const work = talent.works.find((item) => item.slug === workSlug);
  return work ? { talent, work } : null;
}
